language: python
cache: pip

# Matrix of build options
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34-dj111-wt22,py34-dj20-wt22
    - python: 3.5
      env: TOXENV=py35-dj111-wt22,py35-dj20-wt22
    - python: 3.6
      env: TOXENV=py36-dj111-wt22,py36-dj20-wt22
    - python: 3.6
      env: TOXENV=isort,flake8

install:
  - pip install --upgrade pip wheel tox setuptools

script:
  - tox

# vim: sw=2
